spring:
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
      datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3307/forhire_springboot
          username: root
          password: root
      servlet:
        multipart:
            enabled: true
            max-file-size: 15MB
            max-request-size: 10MB
mvk:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: mvkSecretKeyJwt
    
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

USER-MICROSERVICE:
      API:
            getUserNameFromId: http://USER-MICROSERVICE/user/api/getUserNameFromId
            getUserInRequest : http://USER-MICROSERVICE/user/api/getUserInRequest

POST-MICROSERVICE:
      photoLocation: "C:/Users/mail2/Desktop/Spring Projects/ForHire-React-Spring/ForHire - Frontend/forhire/public/img/posts"
      
            
